package com.gr.android.trilhaventurus_ex4

class SongsList {
    fun fetchSongs() : List<Song> = listOf(
        Song("Welcome to the Jungle", "3:10"),
        Song("Bohemian Rhapsody", "10:05"),
        Song("Chop Suey!", "5:20"),
        Song("Meu Novo Mundo", "6:25"),
        Song("Blues da Piedade", "7:14"),
        Song("Learn to Fly", "8:31"),
        Song("Going Away to College", "9:45"),
        Song("Dengo", "3:10"),
        Song("Lisboa", "10:05"),
        Song("MILLE", "5:20"),
        Song("You're so Vain", "6:25"),
        Song("Piccole Cose", "7:14"),
        Song("Viceversa", "8:31"),
        Song("Kings of the Weekend", "9:45"),
        Song("Bullet and a Target", "3:10"),
        Song("Upside Down", "10:05"),
        Song("Redemption Song", "5:20"),
        Song("Gruvi Quantico", "6:25"),
        Song("Sei la", "7:14"),
        Song("Without Me", "8:31"),
        Song("Something", "9:45"),
        Song("Passarinhos", "3:10"),
        Song("Shallow", "10:05"),
        Song("Ela Me Chamou Pra Dancar um Ragga", "5:20"),
        Song("Eremita Moderno", "6:25"),
        Song("Il ballo delle incertezze", "7:14"),
        Song("Andiamo a Comandare", "8:31"),
        Song("Sinceramente", "9:45"),
        Song("Senza Pagare", "3:10"),
        Song("Volare", "10:05"),
        Song("Stand By Me", "5:20"),
        Song("Road Tripping'", "6:25"),
        Song("Youth of the Nation", "7:14"),
        Song("Hallelujah", "8:31"),
        Song("Santeria", "9:45"),
    )
}